main:
  - name: Bio
    url: /
    weight: 10
  - name: Education & Experience
    url: /#experience
  - name: Skills & Hobbies
    url: /#s_h
  - name: Awards
    url: /#awards
    weight: 20
  - name: Projects
    url: /#projects
    weight: 30
