main:
  - name: 主页
    url: /
    weight: 10
  - name: 论文
    url: /#papers
    weight: 11
  - name: 论坛
    url: /#talks
    weight: 12
  - name: 新闻
    url: /#news
    weight: 13
  - name: 经历
    url: experience/
    weight: 20
  - name: 项目
    url: projects/
    weight: 30
  - name: 教学
    url: teaching/
    weight: 40
